# Generated by Django 2.2.25 on 2025-08-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email_host', models.EmailField(max_length=254, verbose_name='默认邮箱')),
                ('email_port', models.CharField(default=25, max_length=50, verbose_name='邮箱端口号')),
                ('email_host_pwd', models.CharField(max_length=100, verbose_name='授权码')),
                ('default_from_email', models.EmailField(max_length=254, verbose_name='默认发件邮箱')),
                ('subject', models.CharField(default='CrawlSpace爬虫管理系统', max_length=200, verbose_name='邮箱主题')),
                ('from_email', models.EmailField(max_length=254, verbose_name='发件邮箱')),
                ('recipient_list', models.TextField(verbose_name='收件人列表')),
                ('email_content', models.TextField(default='\n    <!DOCTYPE html>\n    <html lang="en">\n    <head>\n        <meta charset="UTF-8">\n        <title>Crawlspace邮件通知设置</title>\n    </head>\n    <body>\n    <table>\n            <tr>\n                <th>主机</th>\n                <th>项目</th>\n                <th>爬虫</th>\n                <th>规则</th>\n                <th>任务</th>\n                <th>状态</th>\n                <th>开始时间</th>\n                <th>结束时间</th>\n            </tr>\n            <tr>\n            <td>{0}</td>\n            <td>{1}</td>\n            <td>{2}</td>\n            <td>{3}</td>\n            <td>{4}</td>\n            <td>{5}</td>\n            <td>{6}</td>\n            <td>{7}</td>\n        </tr>\n    </table>\n        <p style="font-size:30px;color:red;">爬虫造反啦！管理员快点啊！看看是不是来活了！</p>\n        <p><button style="color:red"><a href="{8}">不再邮件通知该任务！</a></button></p>\n    </body>\n    </html>\n        ', verbose_name='邮箱模板')),
                ('unit', models.CharField(choices=[('H', 'hour'), ('M', 'minutes'), ('D', 'days')], max_length=10, verbose_name='时间单位')),
                ('interval_send_email', models.CharField(max_length=10, verbose_name='邮箱发送间隔时间')),
                ('email_enable', models.BooleanField(default=True, verbose_name='是否启用邮箱')),
                ('tls', models.BooleanField(default=False, verbose_name='是否启动TLS链接')),
                ('host', models.URLField(default='http://127.0.0.1:8000', verbose_name='服务器域名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '邮件配置信息',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.CharField(max_length=200, verbose_name='爬虫项目')),
                ('spidername', models.CharField(max_length=200, verbose_name='爬虫名称')),
                ('rulefile', models.CharField(max_length=200, verbose_name='规则名称')),
                ('client', models.CharField(max_length=300, verbose_name='主机信息')),
                ('jobid', models.CharField(max_length=300, verbose_name='运行任务ID')),
                ('status', models.CharField(blank=True, max_length=300, null=True, verbose_name='运行状态')),
                ('start_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='开始时间')),
                ('end_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='完成时间')),
                ('email_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='邮件状态')),
                ('msg', models.TextField(blank=True, null=True, verbose_name='邮件详情')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '邮件通知任务',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['jobid'], name='monitor_not_jobid_e74a9e_idx'),
        ),
        migrations.AddIndex(
            model_name='emailinfo',
            index=models.Index(fields=['email_host'], name='monitor_ema_email_h_82cbe8_idx'),
        ),
    ]
