# Generated by Django 2.2.25 on 2025-08-01 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_apscheduler', '0008_remove_djangojobexecution_started'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('ip', models.CharField(blank=True, max_length=255, null=True)),
                ('port', models.IntegerField(blank=True, default=6800, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('auth', models.IntegerField(blank=True, default=0, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('client_enable', models.IntegerField(choices=[(1, '启用'), (2, '关闭')], default=2, verbose_name='节点任务监控')),
            ],
            options={
                'verbose_name_plural': '主机配置',
            },
        ),
        migrations.CreateModel(
            name='Deploy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('deployed_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='spider.Client')),
            ],
            options={
                'verbose_name_plural': '部署信息',
            },
        ),
        migrations.CreateModel(
            name='PackagePath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.TextField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, default='', max_length=255)),
                ('fullpath', models.TextField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': '项目仓库',
            },
        ),
        migrations.CreateModel(
            name='TaskStatusList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.CharField(max_length=200, verbose_name='爬虫项目')),
                ('spidername', models.CharField(max_length=200, verbose_name='爬虫名称')),
                ('rulefile', models.CharField(max_length=200, verbose_name='规则名称')),
                ('jobid', models.CharField(max_length=300, verbose_name='运行任务ID')),
                ('status', models.CharField(blank=True, max_length=300, null=True, verbose_name='运行状态')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('notifications_enable', models.IntegerField(choices=[(1, '启用'), (2, '关闭')], default=1, verbose_name='邮件通知启用')),
                ('package', models.CharField(blank=True, max_length=255, null=True, verbose_name='项目仓库')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='spider.Client')),
            ],
            options={
                'verbose_name_plural': '运行任务',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TaskCron',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.CharField(max_length=200, verbose_name='爬虫项目')),
                ('spidername', models.CharField(max_length=200, verbose_name='爬虫名称')),
                ('rulefile', models.CharField(max_length=200, verbose_name='规则名称')),
                ('configuration', models.TextField(blank=True, max_length=500, null=True, verbose_name='定时任务的详情')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_apscheduler.DjangoJob')),
            ],
            options={
                'verbose_name_plural': '定时任务',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('egg', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.FloatField(blank=True, max_length=100, null=True)),
                ('configuration', models.TextField(blank=True, null=True)),
                ('configurable', models.IntegerField(blank=True, default=0)),
                ('built_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('package', models.CharField(blank=True, max_length=255, null=True)),
                ('clients', models.ManyToManyField(through='spider.Deploy', to='spider.Client')),
            ],
            options={
                'verbose_name_plural': '项目打包',
            },
        ),
        migrations.AddField(
            model_name='deploy',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='spider.Project'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['name'], name='spider_clie_name_abdc00_idx'),
        ),
        migrations.AddIndex(
            model_name='taskstatuslist',
            index=models.Index(fields=['project', 'spidername', 'jobid', 'notifications_enable'], name='spider_task_project_6e919f_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcron',
            index=models.Index(fields=['rulefile'], name='spider_task_rulefil_f345a1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deploy',
            unique_together={('client', 'project')},
        ),
    ]
